services:
  caddy:
    image: caddy:alpine
    command: caddy reverse-proxy --from $JUPYTERLAB_DOMAIN --to jupyterlab:8080
    depends_on:
      - jupyterlab
  jupyterlab:
    image: imwithye/jupyterlab
    environment:
      - PORT=8080
      - JUPYTERLAB_TOKEN=${JUPYTERLAB_TOKEN}
