name: Build Docker Image

on:
  push:
    branches:
    - 'main'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
