name: "deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://dokku@ssh.dokku.yiwei.dev:22/jupyterlab"
          branch: main
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
